repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: mixed-line-ending
        - id: check-merge-conflict
        - id: check-executables-have-shebangs
        - id: check-json
        - id: check-yaml
        - id: check-toml

    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.22.0
      hooks:
        - id: markdownlint

    - repo: https://github.com/asottile/pyupgrade
      rev: v2.1.0
      hooks:
        - id: pyupgrade
          args: [--py36-plus]

    - repo: https://github.com/asottile/seed-isort-config
      rev: v2.1.0
      hooks:
        - id: seed-isort-config
          args: [--application-directories=src/]
          exclude: ^tests/.*$|^example/.*$

    - repo: https://github.com/timothycrosley/isort
      rev: 4.3.21
      hooks:
        - id: isort
          additional_dependencies: ["isort[pyproject]"]

    - repo: https://github.com/psf/black
      rev: 19.10b0
      hooks:
        - id: black

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
        - id: debug-statements
        - id: check-docstring-first
        - id: flake8
          additional_dependencies:
            - flake8-bugbear
